name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        run: |
          cp /home/skyie/end-to-end-mlops-pipeline/.env .
          docker compose up -d --build
